<?xml version="1.0"?>
<package format="3">
  <name>dobot_vision_rgbd</name>
  <version>0.1.0</version>
  <description>Rule-based RGB-D shape, color, depth and geometry detector.</description>
  <maintainer email="bbcontact@example.com">bbcontact</maintainer>
  <license>MIT</license>
  <depend>rclpy</depend>
  <depend>sensor_msgs</depend>
  <exec_depend>orbbec_camera_msgs</exec_depend>
  <depend>std_msgs</depend>
  <depend>cv_bridge</depend>
  <depend>message_filters</depend>
  <exec_depend>python3-opencv</exec_depend>
  <exec_depend>python3-numpy</exec_depend>
  <exec_depend>python3-yaml</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <test_depend>python3-pytest</test_depend>
  <export><build_type>ament_python</build_type></export>
</package>
